---
- name: Install PostgreSQL 
  apt: 
    name: '{{ item }}' 
    state: present
  become: true
  with_items: 
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Ensure PostgreSQL data directory exists
  become: true
  file:
    path: "{{ postgresql_data_dir }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: Create airflow DB user
  postgresql_user:
    name: airflow_db
    password: airflow_db 
    state: present
    role_attr_flags: CREATEDB,SUPERUSER
  become_user: postgres
  become: true

- name: Create new PostgreSQL database
  postgresql_db:
    name: "airflow_metadata"
    login_user: "airflow_db"
    login_password: "airflow_db"
    login_host: localhost 
    state: present
  become_user: postgres
  become: true