---

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
  become: true

- name: Install nginx 
  yum: 
    name: nginx
    update_cache: yes
  become: true

- name: Create nginx sites directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root 
    group: root
    mode: 755 
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "ssl"
  become: true

- name: Copy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 644
  become: true

- name: Copy SSL key
  copy:
    src: files/nginx.key
    dest: /etc/nginx/ssl/nginx.key
    owner: root
    mode: 644
  become: true 

- name: Copy SSL cert
  copy:
    src: files/nginx.crt
    dest: /etc/nginx/ssl/nginx.crt
    owner: root
    mode: 644
  become: true 

- name: copy index.html
  template: 
    src: templates/index.html.j2 
    dest: /usr/share/nginx/html/index.html
    mode: 0644
  become: true

- name: restart nginx
  service: 
    name: nginx 
    state: restarted
  become: true
  # when: configure_nginx_conf|changed