---
- name: Check if miniconda is installed
  become: yes
  stat:
    path: '{{ miniconda_conda_bin }}'
  changed_when: false
  register: miniconda_conda_binary

- when: not miniconda_conda_binary.stat.exists
  block:
    - name: Download miniconda installer
      become: yes
      become_user: root
      get_url:
        url: "{{miniconda_installer_url}}"
        dest: /tmp/{{miniconda_installer_sh}}
        mode: 0755

    - name: Install miniconda
      become: yes
      command: "/tmp/{{miniconda_installer_sh}} -b -p {{miniconda_install_dir}}"
      args:
        creates: "{{miniconda_install_dir}}"

    - name: Symlink miniconda
      become: yes
      file:
        src: "{{ miniconda_install_dir }}"
        dest: "{{ miniconda_link_dir }}"
        state: link

  always:
  - name:  Delete miniconda installer
    become: yes
    become_user: root
    file:
      path: "/tmp/{{miniconda_installer_sh}}"
      state: absent

- name: Create conda symbolic link
  become: yes
  file:
    src: "{{ miniconda_install_dir }}/etc/profile.d/conda.sh"
    dest: "/etc/profile.d/conda.sh"
    state: link